# Generated by Django 4.0.5 on 2022-06-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='is_public',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('На Модерацию', 'На Модерацию'), ('Отклонено', 'Отклонено'), ('Опубликована', 'Опубликована')], default=('Опубликована', 'Опубликована'), max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
